presets:
  link:
    default:
      latency: 5ns
      throughput: 100Gbps
      ingress_buffer_size: 1000000B
      egress_buffer_size: 1000000B
  connection:
    default:
      data_to_send: 1500000B
      mplb: round_robin
  flow:
    default:
      type: tcp
      packet_size: 1500B
      cc:
        type: swift
        base_target: 200ns
  switch:
    default:
      ecn:
        min: 0.7
        max: 0.7
        probability: 1.0
packet-spraying:
  type: ecmp

senders_count: 3 # count of senders in topology; for every sender will be created one connection
